[colors]
cursor =  { text = "CellBackground", cursor = "{{theme.cursor}}" }

[colors.primary]
foreground = "{{theme.foreground}}"
background = "{{theme.background}}"

[colors.normal]
black = "{{theme.black}}"
red = "{{theme.red}}"
green = "{{theme.green}}"
yellow = "{{theme.yellow}}"
blue = "{{theme.blue}}"
magenta = "{{theme.magenta}}"
cyan = "{{theme.cyan}}"
white = "{{theme.white}}"

[colors.bright]
black = "{{theme.light_black}}"
red = "{{theme.light_red}}"
green = "{{theme.light_green}}"
yellow = "{{theme.light_yellow}}"
blue = "{{theme.light_blue}}"
magenta = "{{theme.light_magenta}}"
cyan = "{{theme.light_cyan}}"
white = "{{theme.light_white}}"


