bg = "%blue"
input_bg = "%white"
input_color = "%light_blue" 
input_focused_bg = "%blue"
input_focused_border = "%blue"
input_focused_color = "%magenta" 
input_focused_border_color = "%white"
inner_box_bg = "%white" 
inner_box_flowchild_bg = "%white"
inner_box_flowchild_focused_bg = "%blue"
outer_box_bg = "%white"
text_bg = "%white"
text = "%black"
scroll = "%white"
