
## Work in progress 
## Still need to templatize some dots
[profiles.argonaut]
vars = [ "bombadil/themes/argonaut.toml" ]

[profiles.argonaut.dots]
alacritty = { source= "bombadil/themes/argonaut.toml" }

[profiles.ayu_dark]
vars = [ "bombadil/themes/ayu_dark.toml" ]

[profiles.base16_default_dark]
vars = [ "bombadil/themes/base16_default_dark.toml" ]

[profiles.campbell]
vars = [ "bombadil/themes/campbell.toml" ]

[profiles.challenger_deep]
vars = [ "bombadil/themes/challenger_deep.toml" ]

[profiles.Cobalt2]
vars = [ "bombadil/themes/Cobalt2.toml" ]

[profiles.cyber_punk_neon]
vars = [ "bombadil/themes/cyber_punk_neon.toml" ]

[profiles.darcula]
vars = [ "bombadil/themes/darcula.toml" ]

[profiles.dracula]
vars = [ "bombadil/themes/dracula.toml" ]

[profiles.falcon]
vars = [ "bombadil/themes/falcon.toml" ]

[profiles.gotham]
vars = [ "bombadil/themes/gotham.toml" ]

[profiles.gruvbox_dark]
vars = [ "bombadil/themes/gruvbox_dark.toml" ]

[profiles.gruvbox_light]
vars = [ "bombadil/themes/gruvbox_light.toml" ]
