#!/bin/sh

windows="$(eww windows)"
wildcard='*'
open_bar="true"

while IFS= read -r window; do
    if [[ "${window}" == "$wildcard"bar ]]; then 
      eww close bar
      open_bar="false"
    fi
done <<< "$windows"

if [[ "$open_bar" == "true" ]]; then 
  eww open bar
fi