main_text_color ="#ffffff"
border_color = "#94ddff"
bar_urgent = "#FF4352"
workspaces_fg = "%main_text_color"
worspace_bg = "%light_blue"
worspace_focused_bg = "%light_green"
bar_clock_bg = "#4d91b6"
bar_clock_fg = "%main_text_color"
battery_bg = "#4d91b6"
battery_fg = "%main_text_color"
battery_charging_fg = "%main_text_color"
battery_charging_bg = "#4d91b6"
battery_critical_not_charging_fg= "%main_text_color"
battery_critical_not_charging_bg="#f53c3c"
blink_bg = "%main_text_color"
blink_fg = "#000000"
label_focused = "#000000"
network_bg = "#56a4f7"
network_disconnected = "#f53c3c"
pulse_audio_bg = "#4d91b6"
pulse_audio_fg = "%main_text_color"
pulse_audio_muted_bg = "#90b1b1"
tray_bg = "#4d91b6"
idle_inibitor_bg = "#4d91b6"
idle_inibitor_bg_activated = "#ecf0f1"
