#!/bin/sh

export PATH="$HOME/.cargo/bin:$PATH"
export PATH=$PATH:/usr/node_modules/.bin
export BAT_STYLE=plain,snip,header
export PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
export SHELL_RC=~/dotfiles/zsh/zshrc
export NVIMRC=~/dotfiles/nvim/init.vim
export XKB_DEFAULT_LAYOUT=fr

export IDEA_JDK=/usr/lib/jvm/jre-jetbrains
export PHPSTORM_JDK=/usr/lib/jvm/jre-jetbrains
export WEBIDE_JDK=/usr/lib/jvm/jre-jetbrains
export PYCHARM_JDK=/usr/lib/jvm/jre-jetbrains
export RUBYMINE_JDK=/usr/lib/jvm/jre-jetbrains
export CL_JDK=/usr/lib/jvm/jre-jetbrains
export DATAGRIP_JDK=/usr/lib/jvm/jre-jetbrains
export GOLAND_JDK=/usr/lib/jvm/jre-jetbrains
export STUDIO_JDK=/usr/lib/jvm/jre-jetbrains

{%- if "agicap" in profiles %}
export GITHUB_PACKAGE_REGISTRY_USERNAME={{secrets.GITHUB_PACKAGE_REGISTRY_USERNAME}}
export GITHUB_PACKAGE_REGISTRY_PASSWORD={{secrets.GITHUB_PACKAGE_REGISTRY_PASSWORD}}
export GITLAB_HANGFIRE_REGISTRY_USERNAME={{secrets.GITLAB_HANGFIRE_REGISTRY_USERNAME}}
export GITLAB_HANGFIRE_REGISTRY_PASSWORD={{secrets.GITLAB_HANGFIRE_REGISTRY_PASSWORD}}
{% endif %}
