# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e

# Editor
export VISUAL="nvim"
[[ $- != *i* ]] && return

# Antigen
source /usr/share/zsh/share/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions
antigen bundle zuxfoucault/colored-man-pages_mod
antigen bundle  zsh-users/zsh-completions
antigen apply

fpath=( ~/.zfunc "${fpath[@]}" )

export EDITOR=nvim
export BAT_THEME="Solarized (dark)"


# Aliases
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias status='systemctl status'
alias restart='sudo systemctl restart'
alias jof='journalctl -u'
alias fjof='journalctl -fu'
alias music='ncmpcpp -s media_library'
alias impmus='beet import ~/Downloads/SoulSeek'
alias vim="nvim"
alias record="wf-recorder -f ${filename}"
alias ll='ls -larth'
alias ls='ls --color=auto'
alias lg='ls |grep'
alias lt='ls -t'
alias lr='ls -rt'
alias lr='ls -rt'
alias wa='watch --color -t'
alias k='kubectl'
alias dc='docker-compose'
alias ovim="nvim"
alias cat="bat"
alias ocat="/usr/bin/cat"
# alias grep='rg'
alias ogrep='/usr/bin/grep'
alias fzf='sk'
alias du='dust'
alias copy='wl-copy'
alias docker-stop-all='docker stop $(docker ps -a -q)'

export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt

prompt off
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
eval "$(fnm env --use-on-cd)"

{% if "desktop" in profiles %}
source /home/okno/.support-tools/install/support-tools-rc.sh ## ADDED BY SUPPORT TOOLS
export CHECKOUT_REPOSITORIES_PATH="/code/Sunday" ## ADDED BY SUPPORT TOOLS
 source /home/okno/.support-tools/install/support-tools-rc.sh ## ADDED BY SUPPORT TOOLS
export CHECKOUT_REPOSITORIES_PATH="/code/Sunday" ## ADDED BY SUPPORT TOOLS

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/okno/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/okno/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/okno/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/okno/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
{% endif %}
