theme_name = "Ayu Light"

base00 = "FAFAFA"
base01 = "F3F4F5"
base02 = "F8F9FA"
base03 = "ABB0B6"
base04 = "828C99"
base05 = "5C6773"
base06 = "242936"
base07 = "1A1F29"
base08 = "F07178"
base09 = "FA8D3E"
base0A = "F2AE49"
base0B = "86B300"
base0C = "4CBF99"
base0D = "36A3D9"
base0E = "A37ACC"
base0F = "E6BA7E"

gtk_colors = """
@define-color base00  #FAFAFA;
@define-color base01  #F3F4F5;
@define-color base02  #F8F9FA;
@define-color base03  #ABB0B6;
@define-color base04  #828C99;
@define-color base05  #5C6773;
@define-color base06  #242936;
@define-color base07  #1A1F29;
@define-color base08  #F07178;
@define-color base09  #FA8D3E;
@define-color base0A  #F2AE49;
@define-color base0B  #86B300;
@define-color base0C  #4CBF99;
@define-color base0D  #36A3D9;
@define-color base0E  #A37ACC;
@define-color base0F  #E6BA7E;
"""

scss_colors = """
$base00: #FAFAFA;
$base01: #F3F4F5;
$base02: #F8F9FA;
$base03: #ABB0B6;
$base04: #828C99;
$base05: #5C6773;
$base06: #242936;
$base07: #1A1F29;
$base08: #F07178;
$base09: #FA8D3E;
$base0A: #F2AE49;
$base0B: #86B300;
$base0C: #4CBF99;
$base0D: #36A3D9;
$base0E: #A37ACC;
$base0F: #E6BA7E;
"""
