base00 = "0F1419"
base01 = "131721"
base02 = "272D38"
base03 = "3E4B59"
base04 = "BFBDB6"
base05 = "E6E1CF"
base06 = "E6E1CF"
base07 = "F3F4F5"
base08 = "F07178"
base09 = "FF8F40"
base0A = "FFB454"
base0B = "B8CC52"
base0C = "95E6CB"
base0D = "59C2FF"
base0E = "D2A6FF"
base0F = "E6B673"

gtk_colors = """
@define-color base00  #0F1419;
@define-color base01  #131721;
@define-color base02  #272D38;
@define-color base03  #3E4B59;
@define-color base04  #BFBDB6;
@define-color base05  #E6E1CF;
@define-color base06  #E6E1CF;
@define-color base07  #F3F4F5;
@define-color base08  #F07178;
@define-color base09  #FF8F40;
@define-color base0A  #FFB454;
@define-color base0B  #B8CC52;
@define-color base0C  #95E6CB;
@define-color base0D  #59C2FF;
@define-color base0E  #D2A6FF;
@define-color base0F  #E6B673;
"""

scss_colors = """
$base00: #0F1419;
$base01: #131721;
$base02: #272D38;
$base03: #3E4B59;
$base04: #BFBDB6;
$base05: #E6E1CF;
$base06: #E6E1CF;
$base07: #F3F4F5;
$base08: #F07178;
$base09: #FF8F40;
$base0A: #FFB454;
$base0B: #B8CC52;
$base0C: #95E6CB;
$base0D: #59C2FF;
$base0E: #D2A6FF;
$base0F: #E6B673;
"""

