theme_name = "Generated Theme"

base00 = "040C1C"
base01 = "041423"
base02 = "040C24"
base03 = "04142F"
base04 = "84A4B4"
base05 = "6EACCB"
base06 = "ADA4B4"
base07 = "C0E1ED"
base08 = "AA26B8"
base09 = "B82659"
base0A = "B86126"
base0B = "A1B826"
base0C = "34B826"
base0D = "26B886"
base0E = "267DB8"
base0F = "3C26B8"

gtk_colors = """
@define-color base00  #040C1C;
@define-color base01  #041423;
@define-color base02  #040C24;
@define-color base03  #04142F;
@define-color base04  #84A4B4;
@define-color base05  #6EACCB;
@define-color base06  #ADA4B4;
@define-color base07  #C0E1ED;
@define-color base08  #AA26B8;
@define-color base09  #B82659;
@define-color base0A  #B86126;
@define-color base0B  #A1B826;
@define-color base0C  #34B826;
@define-color base0D  #26B886;
@define-color base0E  #267DB8;
@define-color base0F  #3C26B8;
"""

scss_colors = """
$base00: #040C1C;
$base01: #041423;
$base02: #040C24;
$base03: #04142F;
$base04: #84A4B4;
$base05: #6EACCB;
$base06: #ADA4B4;
$base07: #C0E1ED;
$base08: #AA26B8;
$base09: #B82659;
$base0A: #B86126;
$base0B: #A1B826;
$base0C: #34B826;
$base0D: #26B886;
$base0E: #267DB8;
$base0F: #3C26B8;
"""
