base00 = "191724"
base01 = "1f1d2e"
base02 = "26233a"
base03 = "6e6a86"
base04 = "908caa"
base05 = "e0def4"
base06 = "e0def4"
base07 = "524f67"
base08 = "eb6f92"
base09 = "f6c177"
base0A = "ebbcba"
base0B = "31748f"
base0C = "9ccfd8"
base0D = "c4a7e7"
base0E = "f6c177"
base0F = "524f67"

gtk_colors = """
@define-color base00  #191724;
@define-color base01  #1f1d2e;
@define-color base02  #26233a;
@define-color base03  #6e6a86;
@define-color base04  #908caa;
@define-color base05  #e0def4;
@define-color base06  #e0def4;
@define-color base07  #524f67;
@define-color base08  #eb6f92;
@define-color base09  #f6c177;
@define-color base0A  #ebbcba;
@define-color base0B  #31748f;
@define-color base0C  #9ccfd8;
@define-color base0D  #c4a7e7;
@define-color base0E  #f6c177;
@define-color base0F  #524f67;
"""

scss_colors = """
$base00: #191724;
$base01: #1f1d2e;
$base02: #26233a;
$base03: #6e6a86;
$base04: #908caa;
$base05: #e0def4;
$base06: #e0def4;
$base07: #524f67;
$base08: #eb6f92;
$base09: #f6c177;
$base0A: #ebbcba;
$base0B: #31748f;
$base0C: #9ccfd8;
$base0D: #c4a7e7;
$base0E: #f6c177;
$base0F: #524f67;
""""
