base00 = "191724"
base01 = "1f1d2e"
base02 = "26233a"
base03 = "6e6a86"
base04 = "908caa"
base05 = "e0def4"
base06 = "e0def4"
base07 = "524f67"
base08 = "eb6f92"
base09 = "f6c177"
base0A = "ebbcba"
base0B = "31748f"
base0C = "9ccfd8"
base0D = "c4a7e7"
base0E = "f6c177"
base0F = "524f67"

[theme]
font = "Fira Code 10"
background = "#191724"
foreground = "#cbced0"
text = "#1c1e26"
cursor = "#cbced0"
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

light_black = "#6e6a86"
light_red = "#eb6f92"
light_green = "#31748f"
light_yellow = "#f6c177"
light_blue = "#9ccfd8"
light_magenta = "#c4a7e7"
light_cyan = "#ebbcba"
light_white = "#e0def4"
