
background = "#222324"
foreground = "#BABABA"
text = "#FF261E"
cursor = "#FF261E"

black = "#000000"
red = "#E8341C"
green = "#68C256"
yellow = "#F2D42C"
blue = "#1C98E8"
magenta = "#8E69C9"
cyan = "#1C98E8"
white = "#BABABA"

light_black = "#666666"
light_red = "#E05A4F"
light_green = "#77B869"
light_yellow = "#EFD64B"
light_blue = "#387CD3"
light_magenta = "#957BBE"
light_cyan = "#3D97E2"
light_white = "#BABABA"