[secrets]
GITHUB_PACKAGE_REGISTRY_USERNAME = """
hQEMA6a3l9gLmfGAAQf/SO4StZ4pIlGUiWFg/JpeSq5FhuYoxj646JUw4ckgfgtI
1V6KF4+N8lUjPpo2AcoGdjIjgMnectyRnq9pVwdukc+yCjbhBrHMApYYYPY4NSEC
HogwAVasK+t8MxG4GmRxNTTuGm7dFdAeMAbIcCkDjiEZ0/rdCCIM6J9rl8h85Gx/
lJj2LkwaV2H7JWqggDDNciCbMM+/lz5ZGLkhVHXOdYEe/dpnpUzyUnTVEh0gd4ds
9YKHVdvu2uiLXLGFtm/0nYDVoHIXqcEM2ruSEVjm8AFOQ9rzxBBKDHo2OAqLNKLR
eA99QUuEI/0kdDMdWoljz9bSGcgYr4cH7wMLvO6R4tJCAfPbjTUQ8W4wW2wF37cE
Sj94FbhsZDTlJhMvttYdsW2yxT/hrxyxV/r00GP2Utxc5/kO0i6eWCFbOqUKh5zq
5h8e
=oJQa
"""
GITHUB_PACKAGE_REGISTRY_PASSWORD = """
hQEMA6a3l9gLmfGAAQf+NglN/1qNDKkl7LyFSkhsuBeVkV+Z+tm+SFryVkGx+a9j
1MPnKczyOrdroqbcqk8SU0U9PnatVgO8FO4ggemIHQnkEze2GgzeaGIuwUbwhc8p
+6eEaj75it/RXEKwIUjA/JSqmDe2XPWVS03jUd350UV1l475nStPSGdOeDzty/bI
FOKUcuKV2vwHc3pccwkTaHSZ1BkPEpTeOaWPzOKoj/SF327ZTRQ2/HLrrcGZ/Jqu
TQWhIl4PzIJxEbkK7NQscBLwPE8zngDYWAMfB8CBQ1Za7Zi/oMBgQxavsmPK5s0l
imYJBsxKfpjJczzjlVgzzC6yDBdA8YK137C9hbPrCNJjAenA+jXmJDFRLElX19Ci
jQfVhBIp2EEIvZHcloXYnzGakNlFR8e/vH3iOvKlauTFK9k+g8vM8DJvfbv7tgko
5SUQ6PB1qhgFacqG/1ZifQQyhAuw4WtJ21u9MM6uqkEUp1IR
=R3Fe
"""
GITLAB_HANGFIRE_REGISTRY_USERNAME = """
hQEMA6a3l9gLmfGAAQgAhcM9dVg8lmuUks7WxgFQER6S3OmNmIgJxsz9HOJOb+E+
6SWrfvrpoaUd9lSkuUOpfoYd9FlFgvFGXS5wNwaeNh/MDU76zPd0p0X3/0s/tjEx
w8yGdUwoetY/BJB0mo7qaCqROiAfa9N7fKz6jWWhefNTrIEJRO/+055/PtArGpaT
5n1iOFpqKaK+6fuG+KpcRTnEed+unmlAvDhexuDLHtojoZ/CipzT24IW+OlCgplS
i2hgHG/o9jNgFqhMj/IW5NxG+c6vjKIafiJ26B/k6cB9V7/AjT3vlJl+68sj9szL
ztWrXNMFf8W+PuWkgYOa+TR08od2eFfx22titfLap9JBAemr5f5T42ESBK6sJrYZ
zZz7eT/XRlXVWP2u+6nm98kR2PWwE4pTXgF2mEsPNTXgV3Kpra8AkgEYy5hfD2db
Zng=
=tYXk
"""
GITLAB_HANGFIRE_REGISTRY_PASSWORD = """
hQEMA6a3l9gLmfGAAQf9HxGEieD7SjdW5e868vF005/M5TdJ55sOpDzmE6Tpp7F6
g5KjDDXWok6MTV0A2Fmpog8TpkjOP3n1l2ZNPEC4ADR3Mr+8K+LuY1m+iGocWvun
lTg3we05OnttnCRIUYpshQ9l6LEepskQWozUyIwcV9+4t70u0Ubg2eIo+7joN8OD
sKPlxr6SQpeFRXw0ULblAqCDfjTW+K5/I3r5WiXPplk8im/WlgyqjxX/wG63NQmV
T4hsQLpwk6G2VDM1HTN5uvtzzhUN5aRAE367bc5JajqnUEvd7mmqLZYgZ1HGEtie
OilRvQMXX+ksHTO9w2pnjMZE08fnJwLV03qhC3+Lj9JLAe0x4M2LERh58O/XGdVE
pvE0ZubG2PMNli9BIaDEAUShQ0hfZs++LjYIOdJRtWK0WMSpTGzJXfkSUZe1uCje
VJZDg1fEJHBuzcey
=5yWV
"""
