[profiles.i3]
prehooks = ["echo installing i3 dotfiles"]
posthooks = ["i3-msg reload"]

[profiles.i3.dots]
i3 =  { source = "wm/i3/wm", target = ".config/i3" }
polybar =  { source = "wm/i3/polybar", target = ".config/polybar" }
rofi =  { source = "wm/i3/rofi", target = ".config/rofi" }
picom =  { source = "wm/i3/picom", target = ".config/picom" }
autodisplay =  { source = "wm/i3/autodisplay", target = ".config/i3-autodisplay" }
