position = "top"
height = 28

[[start]]
all_monitors = false
type = 'workspaces'

[[center]]
type = "clock"
format = "%d/%m/%Y %H:%M"

[[end]]
type = "tray"

[[end.name_map]]
1 = "{{theme.icons.workspace.1}}"
2 = "{{theme.icons.workspace.2}}"
3 = "{{theme.icons.workspace.3}}"
4 = "{{theme.icons.workspace.4}}"
5 = "{{theme.icons.workspace.5}}"
6 = "{{theme.icons.workspace.6}}"
7 = "{{theme.icons.workspace.7}}"
8 = "{{theme.icons.workspace.8}}"
9 = "{{theme.icons.workspace.9}}"
10 = "{{theme.icons.workspace.10}}"

