---
directory: /mnt/data/Music
library: ~/.config/beets/library.db
plugins: fetchart lyrics lastgenre
import:
    move: true

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
