#!/bin/sh

export PATH="$HOME/.cargo/bin:$PATH"
export PATH=$PATH:/usr/node_modules/.bin
export BAT_STYLE=plain,snip,header
export PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
export MY_ZSHRC=~/.zshrc
export XKB_DEFAULT_LAYOUT=fr


fullscreenshot() {
  date=$(date +%Y-%m-%dT%H:%M:%S%z)
  grim "$HOME/Pictures/Screenshots/screenshot-$date.png" && paplay "$HOME/dotfiles/audio/screenshot.wav"
}

screenshot() {
  date=$(date +%Y-%m-%dT%H:%M:%S%z)
  grim -g "$(slurp)" "$HOME/Pictures/Screenshots/screenshot-$date.png" && paplay "$HOME/dotfiles/audio/screenshot.wav"
}

switch_bombadil_profile() {
  # Allow switching profiles using the wofi launcher/menu program (https://hg.sr.ht/~scoopta/wofi).

  if ! command -v bombadil &> /dev/null; then
      echo "bombadil could not be found" >&2
      exit 1
  fi

  if ! command -v wofi &> /dev/null; then
      echo "wofi could not be found" >&2
      exit 1
  fi

  SELECTED_PROFILE=$(bombadil get profiles | wofi -i -d -p "Switch Toml Bombadil Profile:")

  if [ "$SELECTED_PROFILE" = "default" ]; then
      bombadil link
  else
      bombadil link -p "$SELECTED_PROFILE"
  fi

}

wob_volume() {
    volume=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: front/{ print $5 }' | sed 's/[%|,]//g')
    if [ "$volume" -gt 100 ]; 
    then    
        volume=100
    fi

    echo "$volume __[red]__ __[black]__ __[green]__"
}

