# Zsh 
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl true
zstyle :compinstall filename '$HOME/.zshrc'

# Completion
fpath=(~/dotfiles/zsh/completions $fpath)
autoload -Uz compinit promptinit
compinit

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e

# Editor
export VISUAL="nvim"
[[ $- != *i* ]] && return

# Antigen 
source /usr/share/zsh/share/antigen.zsh 
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions
antigen bundle zuxfoucault/colored-man-pages_mod
antigen apply

export EDITOR=nvim
export BAT_THEME="Solarized (light)"

eval "$(starship init zsh)"

####################
##### ALIASES ######
####################

## Systemctl 
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias status='systemctl status'
alias restart='sudo systemctl restart'
alias jof='journalctl -u'
alias fjof='journalctl -fu'

# Nmcli
alias vpnfacup='nmcli connection up ulille_vpn_etu_udp_v1 --ask'
alias vpnfacdown='nmcli con down ulille_vpn_etu_udp_v1'

## Multimedia 
alias music='ncmpcpp -s media_library'
alias impmus='beet import ~/Downloads/SoulSeek'

## Commons
alias vim="nvim"
alias record="wf-recorder -f ${filename}"
alias ll='ls -larth'
alias ls='ls --color=auto'
alias lg='ls |grep' 
alias lt='ls -t' 
alias lr='ls -rt' 
alias lr='ls -rt' 
alias wa='watch --color -t' 

# Muscle memory tricks
alias k='kubectl'
alias ovim="vim"
alias cat="bat"
alias ocat="/usr/bin/cat"
alias grep='rg'
alias ogrep='/usr/bin/grep'
alias fzf='sk'
alias du='dust'
alias copy='wl-copy'

# Work Alias
alias decatvpn="sudo unshare -f -m -p --mount-proc sudo -u okno sh -c '/usr/local/pulse/pulseUi -S | /usr/local/bin/esets_daemon | /usr/local/bin/rtvscand'"


source /usr/share/autojump/autojump.zsh
