[general]
import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }

[window]
padding = { x = 15, y = 15 }

[terminal]
shell = "/bin/zsh"
