# Default colors
[colors.primary]
background = '#{{base00}}'
foreground = '#{{base05}}'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#{{base00}}'
cursor = '#{{base05}}'

# Normal colors
[colors.normal]
black = '#{{base00}}'
red = '#{{base08}}'
green = '#{{base0B}}'
yellow = '#{{base0A}}'
blue = '#{{base0D}}'
magenta = '#{{base0E}}'
cyan = '#{{base0C}}'
white = '#{{base05}}'

# Bright colors
[colors.bright]
black = '#{{base03}}'
red = '#{{base08}}'
green = '#{{base0B}}'
yellow = '#{{base0A}}'
blue = '#{{base0D}}'
magenta = '#{{base0E}}'
cyan = '#{{base0C}}'
white = '#{{base07}}'

[[colors.indexed_colors]]
index = 16
color = "#{{base09}}"

[[colors.indexed_colors]]
index = 17
color = "#{{base0F}}"

[[colors.indexed_colors]]
index = 18
color = "#{{base01}}"

[[colors.indexed_colors]]
index = 19
color = "#{{base02}}"

[[colors.indexed_colors]]
index = 20
color = "#{{base04}}"

[[colors.indexed_colors]]
index = 21
color = "#{{base06}}"
